"""add metadata

Revision ID: 34298b352974
Revises: 48d63259260a
Create Date: 2022-11-20 04:45:35.138577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34298b352974'
down_revision = '48d63259260a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('receiver_name', sa.String(), nullable=True),
    sa.Column('receiver_name2', sa.String(), nullable=True),
    sa.Column('receiver_last_name', sa.String(), nullable=True),
    sa.Column('receiver_address', sa.String(), nullable=True),
    sa.Column('receiver_pesel', sa.String(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('sender_name2', sa.String(), nullable=True),
    sa.Column('sender_phone', sa.String(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=True),
    sa.Column('sender_epuap', sa.String(), nullable=True),
    sa.Column('sender_address', sa.String(), nullable=True),
    sa.Column('unp', sa.String(), nullable=True),
    sa.Column('znak_sprawy', sa.String(), nullable=True),
    sa.Column('tytul_sprawy', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('nip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_id'), 'metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_id'), table_name='metadata')
    op.drop_table('metadata')
    # ### end Alembic commands ###
