"""Add settings

Revision ID: 409ed203acb9
Revises: c0adae737a5d
Create Date: 2022-11-19 17:50:45.890755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409ed203acb9'
down_revision = 'c0adae737a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('orientation', sa.String(), nullable=False),
    sa.Column('pdf_version', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('min_margin_top', sa.Float(), nullable=False),
    sa.Column('min_margin_bottom', sa.Float(), nullable=False),
    sa.Column('min_margin_side', sa.Float(), nullable=False),
    sa.Column('protections_allowed', sa.Boolean(), nullable=False),
    sa.Column('name_banned_symbols', sa.String(), nullable=False),
    sa.Column('allow_leading_space', sa.Boolean(), nullable=False),
    sa.Column('allow_trailing_space', sa.Boolean(), nullable=False),
    sa.Column('encoding', sa.String(), nullable=False),
    sa.Column('filename_max_length', sa.Integer(), nullable=False),
    sa.Column('composite_pdf', sa.Boolean(), nullable=False),
    sa.Column('allow_unused_links_etc', sa.Boolean(), nullable=False),
    sa.Column('allow_hidden_layer_info', sa.Boolean(), nullable=False),
    sa.Column('embedded_font', sa.Boolean(), nullable=False),
    sa.Column('min_font_single_color_single_elem', sa.Float(), nullable=False),
    sa.Column('min_font_single_color_double_elem', sa.Float(), nullable=False),
    sa.Column('min_font_multi_color_single_elem', sa.Float(), nullable=False),
    sa.Column('min_font_multi_color_double_elem', sa.Float(), nullable=False),
    sa.Column('min_line_thickness', sa.Float(), nullable=False),
    sa.Column('min_line_thickness_other', sa.Float(), nullable=False),
    sa.Column('active_forms', sa.Boolean(), nullable=False),
    sa.Column('color_mode', sa.String(), nullable=False),
    sa.Column('text_color', sa.String(), nullable=False),
    sa.Column('min_dpi', sa.Float(), nullable=False),
    sa.Column('graphic_scale', sa.Float(), nullable=False),
    sa.Column('graphic_color_mode', sa.String(), nullable=False),
    sa.Column('name_max_length', sa.Integer(), nullable=False),
    sa.Column('name_cont_max_length', sa.Integer(), nullable=False),
    sa.Column('street_max_length', sa.Integer(), nullable=False),
    sa.Column('building_number_max_length', sa.Integer(), nullable=False),
    sa.Column('local_number_max_length', sa.Integer(), nullable=False),
    sa.Column('postal_code_max_length', sa.Integer(), nullable=False),
    sa.Column('city_max_length', sa.Integer(), nullable=False),
    sa.Column('country_max_length', sa.Integer(), nullable=False),
    sa.Column('sender_info_max_length', sa.Integer(), nullable=False),
    sa.Column('signature_act_max_length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
