"""make_report_nullable

Revision ID: 48d63259260a
Revises: 7b3df0c5489c
Create Date: 2022-11-20 03:23:17.275111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d63259260a'
down_revision = '7b3df0c5489c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'format',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'orientation',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'pdf_version',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_margin_top',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_margin_bottom',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_margin_side',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'protections_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'name_banned_symbols',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'allow_leading_space',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'allow_trailing_space',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'encoding',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'filename_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'composite_pdf',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'allow_unused_links_etc',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'allow_hidden_layer_info',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'embedded_font',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_font_single_color_single_elem',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_font_single_color_double_elem',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_font_multi_color_single_elem',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_font_multi_color_double_elem',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_line_thickness',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_line_thickness_other',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'active_forms',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'color_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'text_color',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'min_dpi',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'graphic_scale',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'graphic_color_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'name_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'name_cont_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'street_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'building_number_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'local_number_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'postal_code_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'city_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'country_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'sender_info_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('report', 'signature_act_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_report_id', table_name='report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_report_id', 'report', ['id'], unique=False)
    op.alter_column('report', 'signature_act_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'sender_info_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'country_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'city_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'postal_code_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'local_number_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'building_number_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'street_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'name_cont_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'name_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'graphic_color_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'graphic_scale',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_dpi',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'text_color',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'color_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'active_forms',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_line_thickness_other',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_line_thickness',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_font_multi_color_double_elem',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_font_multi_color_single_elem',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_font_single_color_double_elem',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_font_single_color_single_elem',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'embedded_font',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'allow_hidden_layer_info',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'allow_unused_links_etc',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'composite_pdf',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'filename_max_length',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'encoding',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'allow_trailing_space',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'allow_leading_space',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'name_banned_symbols',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'protections_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_margin_side',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_margin_bottom',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'min_margin_top',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'pdf_version',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'orientation',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('report', 'format',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
