"""Add separate margins for both sides

Revision ID: 7143f76d3d85
Revises: 52e143908bb2
Create Date: 2022-11-20 05:35:31.410809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7143f76d3d85'
down_revision = '52e143908bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('min_margin_left', sa.Boolean(), nullable=True))
    op.add_column('report', sa.Column('min_margin_right', sa.Boolean(), nullable=True))
    op.drop_column('report', 'min_margin_side')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('min_margin_side', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('report', 'min_margin_right')
    op.drop_column('report', 'min_margin_left')
    # ### end Alembic commands ###
