"""add doc state

Revision ID: 7759d9f34a00
Revises: cb384cfbdc10
Create Date: 2022-11-19 20:59:47.323159

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql
from app.models.document import DocumentState

# revision identifiers, used by Alembic.
revision = '7759d9f34a00'
down_revision = 'cb384cfbdc10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    document_state = postgresql.ENUM(DocumentState, name="documentstate")
    document_state.create(op.get_bind(), checkfirst=True)
    op.add_column('document', sa.Column('state',  document_state))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'state')
    # ### end Alembic commands ###
