"""add report

Revision ID: 7b3df0c5489c
Revises: 7759d9f34a00
Create Date: 2022-11-19 22:01:56.293844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b3df0c5489c'
down_revision = '7759d9f34a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Boolean(), nullable=False),
    sa.Column('orientation', sa.Boolean(), nullable=False),
    sa.Column('pdf_version', sa.Boolean(), nullable=False),
    sa.Column('min_margin_top', sa.Boolean(), nullable=False),
    sa.Column('min_margin_bottom', sa.Boolean(), nullable=False),
    sa.Column('min_margin_side', sa.Boolean(), nullable=False),
    sa.Column('protections_allowed', sa.Boolean(), nullable=False),
    sa.Column('name_banned_symbols', sa.Boolean(), nullable=False),
    sa.Column('allow_leading_space', sa.Boolean(), nullable=False),
    sa.Column('allow_trailing_space', sa.Boolean(), nullable=False),
    sa.Column('encoding', sa.Boolean(), nullable=False),
    sa.Column('filename_max_length', sa.Boolean(), nullable=False),
    sa.Column('composite_pdf', sa.Boolean(), nullable=False),
    sa.Column('allow_unused_links_etc', sa.Boolean(), nullable=False),
    sa.Column('allow_hidden_layer_info', sa.Boolean(), nullable=False),
    sa.Column('embedded_font', sa.Boolean(), nullable=False),
    sa.Column('min_font_single_color_single_elem', sa.Boolean(), nullable=False),
    sa.Column('min_font_single_color_double_elem', sa.Boolean(), nullable=False),
    sa.Column('min_font_multi_color_single_elem', sa.Boolean(), nullable=False),
    sa.Column('min_font_multi_color_double_elem', sa.Boolean(), nullable=False),
    sa.Column('min_line_thickness', sa.Boolean(), nullable=False),
    sa.Column('min_line_thickness_other', sa.Boolean(), nullable=False),
    sa.Column('active_forms', sa.Boolean(), nullable=False),
    sa.Column('color_mode', sa.Boolean(), nullable=False),
    sa.Column('text_color', sa.Boolean(), nullable=False),
    sa.Column('min_dpi', sa.Boolean(), nullable=False),
    sa.Column('graphic_scale', sa.Boolean(), nullable=False),
    sa.Column('graphic_color_mode', sa.Boolean(), nullable=False),
    sa.Column('name_max_length', sa.Boolean(), nullable=False),
    sa.Column('name_cont_max_length', sa.Boolean(), nullable=False),
    sa.Column('street_max_length', sa.Boolean(), nullable=False),
    sa.Column('building_number_max_length', sa.Boolean(), nullable=False),
    sa.Column('local_number_max_length', sa.Boolean(), nullable=False),
    sa.Column('postal_code_max_length', sa.Boolean(), nullable=False),
    sa.Column('city_max_length', sa.Boolean(), nullable=False),
    sa.Column('country_max_length', sa.Boolean(), nullable=False),
    sa.Column('sender_info_max_length', sa.Boolean(), nullable=False),
    sa.Column('signature_act_max_length', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.alter_column('document', 'state',
               existing_type=postgresql.ENUM('UPLOADED', 'ACCEPT_CONVERSION', 'CONVERT', 'VALIDATE', 'ACCEPT_FIX', 'FIX', name='documentstate'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'state',
               existing_type=postgresql.ENUM('UPLOADED', 'ACCEPT_CONVERSION', 'CONVERT', 'VALIDATE', 'ACCEPT_FIX', 'FIX', name='documentstate'),
               nullable=True)
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
